### ISSUE TITLE
[Feature request] Green is for success, grey is for boring.

### ISSUE THREAD

**Issue by tugend** [jls/nightwatch-html-reporter#10]
A completely nonessential detail for the new design,
indeed I must apologise for mentioning it at all! ^_^
The new grey color is really depressing compared to the
wonderful green color that was used previously to mark
passing tests.

I've just changed it locally, but it does make the screenshots
on the gitpage look much less exciting!

**Comment by jls** [comment]
This issue title made me laugh!  I went back and forth on the grey for a bit.  I could add two new themes default-colorful and compact-colorful that bring back the green colors though so that way you could choose!

**Comment by bbottema** [comment]
Actually, semantically grey would be for disabled or ignored. First time I saw it I thought that those tests were skipped or something. Green or even black would probably be better.

**Comment by jls** [comment]
In 0.2.12 the default and compact themes are back to using green for success.  The gray styles (which I prefer just because of the ability to quickly scan and ignore successes) have moved to default-gray and compact-gray.  Thanks guys!
