### ISSUE TITLE
Generated HTML report is not correct in nightwatch 0.6.4 

### ISSUE THREAD

**Issue by oyeharry** [jls/nightwatch-html-reporter#14]
HTML report is not correct if I use nightwatch 0.6.4. Assertions always appear failed on report and if i click on test case it show me __completed__ and __skip__ instead of test case description.

**Comment by jls** [comment]
I'm able to reproduce this locally, I'm looking into it now.  Thank you!

**Comment by jls** [comment]
Looks like Nightwatch changed the report object that is sent to reporter functions in 0.6.4.  I'm working on a fix but it'll probably be later today or tomorrow.

**Comment by jls** [comment]
Latest version works with Nightwatch 0.6.4.  Thanks again!

**Comment by oyeharry** [comment]
Oh Great! Pleasure! and Thanks for fix!

**Comment by oyeharry** [comment]
Now if one of assertion fail then reporter don't generate report file instead print [object Object] in bash. This issue also occur in nightwatch latest 0.6.5
