### ISSUE TITLE
If one of test fail reporter don't create report file when using reporter 1.0.0 and  nightwatch 0.6.4 & 0.6.5 

### ISSUE THREAD

**Issue by oyeharry** [jls/nightwatch-html-reporter#16]
I am using nightwatch 0.6.4 & latest nightwatch-html-reporter. When running test cases if one of test fail reporter don't create report file instead it show [object Object] on nightwatch 0.6.4 and on 0.6.5 it print some error.

**Comment by jls** [comment]
Duplicate of #15. I'm looking into this now, thank you!

**Comment by jls** [comment]
Resolved in 1.0.1.  Thank you!
