### ISSUE TITLE
HTML reporter shows test failures but in command line and in XML test cases passed.

### ISSUE THREAD

**Issue by newtonflash** [jls/nightwatch-html-reporter#19]
My XML file has the following content:

<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="0"
            tests="2">

  <testsuite name="test"
    errors="0" failures="0" hostname="" id="" package="test" skipped="0"
    tests="2" time="6.783" timestamp="Wed, 03 Jun 2015 08:25:10 GMT">
  
    <testcase name="Login works" time="3.389" assertions="4">
    </testcase>
  
    <testcase name="Login fails" time="3.394" assertions="4">
    </testcase>
  </testsuite>
</testsuites>

but the generatedReport.html file shows it has completed some test and second it skipped.
![screen shot 2015-06-03 at 2 04 45 pm](https://cloud.githubusercontent.com/assets/10302551/7955942/bf0adc10-09f9-11e5-81be-53e628780aa7.png)

**Comment by jls** [comment]
Which version of Nightwatch and which version of nightwatch-html-reporter are you seeing this in? 

I think github garbled some of your XML file, would you be able to send it to me so I can test against it?  If you'd rather it not be public then you could email it to me dev at jls.io.  

Thank you!

**Comment by Alexxxey** [comment]
I had the same problem (no passed cases in report), when for some reason used Nightwatch 0.8.6 and nightwatch-html-report 0.3.1. Solution was simple:
- uninstall 0.3.1
- install the latest one

**Comment by jls** [comment]
Thank you @Alexxxey!
