### ISSUE TITLE
The theme format is not email friendly.

### ISSUE THREAD

**Issue by louiscbotha** [jls/nightwatch-html-reporter#20]
Outlook doesn't display the styles correctly when embedding this report html in the body of an email. This is because of the way how the styles are done which isn't supported by Outlook and some email apps. 

Automatic emailing of these reports isn't necessary used by most people but we are using it in that way.

**Comment by jls** [comment]
Sorry for the delay on this!  Is there something specific about the styles I can change to make it look better in Outlook?  I don't have a good way to test this but I would gladly welcome a pull request!

**Comment by louiscbotha** [comment]
http://stackoverflow.com/questions/5861714/formatting-html-email-for-outlook describes some of the css issues that Outlook have. Basically it comes down to using very simple css to make it compatible.

**Comment by jls** [comment]
So sorry, this got lost in my notes.  I'll see what I can do about creating a low style theme that you could use for email.  In the meantime if you have created one that you are using then a PR would be awesome so I could include it!

**Comment by louiscbotha** [comment]
I've created a PR which includes an outlook compatible theme https://github.com/jls/nightwatch-html-reporter/pull/23.

**Comment by jls** [comment]
Merged in #23, thanks again!
