### ISSUE TITLE
Is it possible to use this with the "--reporter" cmd option of nightwatch?

### ISSUE THREAD

**Issue by Tiagoperes** [jls/nightwatch-html-reporter#22]
I'd like to know if it's possible to use this with the built-in "--report" option of Nightwatch. If yes, what is the file I should refer to?

http://nightwatchjs.org/guide#command-line-options

**Comment by jls** [comment]
I have not seen the --reporter option, let me read a little more about it and figure out what you can pass to get the html reporter to work with it.

**Comment by jls** [comment]
Ok looks like the file you pass for that option has a slightly different interface than the normal reporter.  I'm going to look at adding a more permanent option but in the meantime you can create a new file in your nightwatch directory (wherever you have nightwatch and globals.js file) that basically mimics the globals.js options for the html reporter.

```javascript
var HtmlReporter = require('nightwatch-html-reporter');
var reporter = new HtmlReporter({
	openBrowser: true,
	reportsDirectory: __dirname + '/reports/',
	themeName: 'cover'
});

module.exports = {
  write : function(results, options, done) {
    reporter.fn(results, done);
  }
};
```

Then if you named that file `html-reporter.js` then you would specify the reporter option as `./nightwatch --reporter ./html-reporter.js`

Let me know if that doesn't make sense or if something doesn't work for you!

**Comment by Tiagoperes** [comment]
Thank you. I'll try this :+1:
