### ISSUE TITLE
Customize output report

### ISSUE THREAD

**Issue by santospro** [jls/nightwatch-html-reporter#24]
Hi,

How can I customize the html report to add more information? for example the screenshots..

Thanks

**Comment by jls** [comment]
Hello!

Most of the themes display screenshot information.  You can see an example of it in the default theme at https://github.com/jls/nightwatch-html-reporter/blob/master/lib/themes/default/report.jade#L27-L29.

You can also have a look at https://github.com/jls/nightwatch-html-reporter/blob/master/lib/normalize.js to see the structure of the object passed to the reports in case you wanted to add some data to a theme that we don't already include. 

Hope this helps!
James
