### ISSUE TITLE
Screenshots empty

### ISSUE THREAD

**Issue by adriokn** [jls/nightwatch-html-reporter#26]
I have a test that fails on purpose, but the array of screen shots shown me empty.
Why does this happen?

{ message: 'H2 [Present - H2 element \'Opciones de personalización\' is present]',
       stacktrace: '    at Object.<anonymous> (/var/www/testing/tests/CorporateData/Domains/domain.js:104:19)\n    at HttpRequest.<anonymous> (/var/www/testing/node_modules/nightwatch/lib/index.js:337:20)\n    at HttpRequest.emit (events.js:110:17)\n    at HttpRequest.<anonymous> (/var/www/testing/node_modules/nightwatch/lib/index.js:365:15)\n    at HttpRequest.emit (events.js:118:17)\n    at IncomingMessage.<anonymous> (/var/www/testing/node_modules/nightwatch/lib/http/request.js:155:16)\n    at IncomingMessage.emit (events.js:129:20)\n    at _stream_readable.js:908:16\n    at process._tickCallback (node.js:355:11)',
       failure: 'Expected "found" but got: "not found"',
       screenshots: [],
       isFailure: 'Expected "found" but got: "not found"' } ],
  isFailure: true }

the path is set in the gruntfile.js:

test_settings : {
          default : {
            launch_url : "www",
            selenium_host : "127.0.0.1",
            selenium_port : 4444,
            silent: true,
            screenshots : {
              enabled : true,
              on_failure : true,
              on_error : true,
              path : "./"
            },
            desiredCapabilities: {
              browserName: "chrome",
              "platform": "LINUX",
              javascriptEnabled: true,
              acceptSslCerts: true
            }
          },
          firefox : {
            desiredCapabilities: {
              browserName: "firefox",
              "platform": "LINUX",
              javascriptEnabled: true,
              acceptSslCerts: true
            }
          },
        },

Thanks!!

**Comment by jls** [comment]
Hello!  

Do the screenshots exist on disk in the path you've set for them to be saved?  The screenshots array we get either directly from Nightwatch (if using the reporter option or specifying the reporter in globals.js) or from the XML reports (if using reporter from the command line).

If you're using the reporter on the command line then you may want to check the XML reports nightwatch generates to see if the screenshots are listed in there.  If you're using the reporter option or specifying the reporter in globals.js you may have to open a ticket for Nightwatch since we are just handed that data from them.

**Comment by adriokn** [comment]
Yes, the screenshots are saved in the specified path.
I am confused.. I need help!

Thanks!!

**Comment by jls** [comment]
No problem!  What version of Nightwatch are you using? 

One other thing we can try is to save the data we get from Nightwatch and make sure that the screenshots array is stored in there.

To do that you can specify the saveNightwatch option by opening up your **html-reporter.js** and adding the option saveNightwatch so it looks something like:
```javascript
var HtmlReporter = require('nightwatch-html-reporter');
/* Same options as when using the built in nightwatch reporter option */
var reporter = new HtmlReporter({
    debug: {
        saveNightwatch: './debugNightwatchOutput.txt'
    }
});
```

Then after you run your tests again there should be a debugNightwatchOutput.txt (or whatever you named it).  If you look in that file you should see the screenshots array and let's see what that looks like. 

Let me know and we can go from there!

**Comment by adriokn** [comment]
The output .txt save as follows ():

{
	"passed": 6,
	"failed": 1,
	"errors": 0,
	"skipped": 0,
	"tests": 7,
	"errmessages": [],
	"modules": {
		"CorporateData/Domains/domain": {
			"completed": {
				"Create domain": {
					"passed": 6,
					"failed": 1,
					"errors": 0,
					"skipped": 0,
					"assertions": [
						{
							"message": "ACCESS [Visible - Access to LOGIN succesful]",
							"stacktrace": "",
							"failure": false
						},
						{
							"message": "LOGIN [Visible - Body in window 'LoginOKN' is visible)]",
							"stacktrace": "",
							"failure": false
						},
						{
							"message": "LOGIN [SUCCESFUL]",
							"stacktrace": "",
							"failure": false
						},
						{
							"message": "ACCESS [Present - Access to 'Gestión de entornos' succesful]",
							"stacktrace": "",
							"failure": false
						},
						{
							"message": "BUTTON [Visible - Button 'Nuevo entorno' is visible]",
							"stacktrace": "",
							"failure": false
						},
						{
							"message": "WINDOW [Not present - Window 'Nuevo entorno' is not present]",
							"stacktrace": "",
							"failure": false
						},
						{
							"message": "WINDOW [Present - Window 'Nuevo entorno' is present]",
							"stacktrace": "    at Object.module.exports.Create domain (/var/www/testing/tests/CorporateData/Domains/domain.js:56:5)\n    at Module.call (/var/www/testing/node_modules/nightwatch/lib/runner/module.js:63:34)\n    at /var/www/testing/node_modules/nightwatch/lib/runner/testcase.js:97:29\n    at _fulfilled (/var/www/testing/node_modules/q/q.js:834:54)\n    at self.promiseDispatch.done (/var/www/testing/node_modules/q/q.js:863:30)\n    at Promise.promise.promiseDispatch (/var/www/testing/node_modules/q/q.js:796:13)\n    at /var/www/testing/node_modules/q/q.js:556:49\n    at runSingle (/var/www/testing/node_modules/q/q.js:137:13)\n    at flush (/var/www/testing/node_modules/q/q.js:125:13)\n    at process._tickCallback (node.js:355:11)",
							"failure": "Expected \"found\" but got: \"not found\""
						}
					],
					"time": "17.57"
				}
			},
			"skipped": [
				"Edit domain",
				"Delete domain"
			],
			"time": "17.57",
			"timestamp": "Wed, 20 Apr 2016 14:22:09 GMT",
			"group": "Domains",
			"tests": 3,
			"failures": 1,
			"errors": 0,
			"errmessages": []
		}
	},
	"assertions": 7
}

**Comment by jls** [comment]
It doesn't look like the assertion block has the screenshots in there.  Normally that block looks like:

```javascript
{
  "message": "Timed out while waiting for element <button[name=btnGFAIL]> to be present for 1000 milliseconds.",
  "stacktrace": "Timed out while ...    at _stream_readable.js:944:16",
  "failure": "Expected \"visible\" but got: \"not found\"",
  "screenshots": [
      "/Users/userOne/Code/project/tests/nightwatch/screenshots/ERROR_Thu-Apr-21-2016-153446-GMT-0400.png"
  ]
}
```

This may be a bug in Nightwatch.  It may be related to this issue on Nightwatch https://github.com/nightwatchjs/nightwatch/issues/673 but I'm not sure.  

One way to test is to switch one of your tests so before it fails the first assert call, have it fail on something like `waitForElementVisible` looking for an element that doesn't exist.  If the screenshot for that works then you may be seeing the same problem as in that Nightwatch issue.

**Comment by jls** [comment]
Closing this out since it seems like it could be a problem with nightwatch instead of the reporter.
