### ISSUE TITLE
screenshots should use relative path to output file

### ISSUE THREAD

**Issue by martineez** [jls/nightwatch-html-reporter#29]
Hi,
could you please change screenshots links as a relative paths to output file
(e.g. in cover theme) it would be valid after executing in jenkins.
Thanks a lot!

**Comment by jbehling** [comment]
+1 to this. I use this with jenkins html reporter as well, image format is hard-coded to path as it appears on the slave

**Comment by jls** [comment]
Right now we just use the path given to the reporter by Nightwatch but I could switch to be relative.  I'll work on this in the next couple of days.

**Comment by jls** [comment]
version 1.0.8 added an option (`-r` on the command line or `relativeScreenshots: true` for reporter interface) to convert screenshot paths from absolute to relative paths.

Let me know if you all have any problems with it!  thank you!
