### ISSUE TITLE
--output option doesn't use relative path after npm update

### ISSUE THREAD

**Issue by jharthun2901** [jls/nightwatch-html-reporter#33]
I'm using the following to generate reports from the command line:

nightwatch-html-reporter -d ./reports/junit -o ../html/SummaryReport.html -t compact

The report was being create in the "html" folder.  This morning, I ran "npm update" on my project and now the report gets created in the "junit" folder instead of the "html" folder.  

What happened and how can I fix it?  Thanks.

**Comment by jharthun2901** [comment]
I rolled back nightwatch-html-reporter to version 1.0.4 and the issue was resolved.

**Comment by jls** [comment]
Found the issue and going to work on a fix for this tonight

**Comment by jls** [comment]
Should be fixed for you now in 1.0.6!  Thank you!
