### ISSUE TITLE
allow custom template jade file 

### ISSUE THREAD

**Issue by phiphou** [jls/nightwatch-html-reporter#37]
Would be fun if we could put our own jade theme file anywhere we want and specify it in the opts, don"t you think ?

**Comment by jls** [comment]
That's a great idea! I'll see if I can get to it soon. Thanks!

**Comment by phiphou** [comment]
Thank you, would allow us to make our own templates based on the provided ones ;)

**Comment by jls** [comment]
This was addressed in pull request #51
