### ISSUE TITLE
In nightwatch 0.9.12 the reporter hook prototype has been changed and it no longer has a callback.

### ISSUE THREAD

**Issue by mehmetg** [jls/nightwatch-html-reporter#38]
Without the callback the plugin does not work as intended.

`
...
 Error while running [Test / reporter]:
  TypeError: done is not a function
...
`

**Comment by jls** [comment]
Aw bummer, ok I'll see if I can take a look here soon.

**Comment by jls** [comment]
@mehmetg From their docs (http://nightwatchjs.org/guide#custom-reporter) and the builtin junit reporter (https://github.com/nightwatchjs/nightwatch/blob/master/lib/runner/reporters/junit.js) it doesn't look like anything has changed. 

Could you point me to where you see the API for the reporter has changed?  (I'm not questioning, I'm just having trouble finding where or when it was changed).

Thanks!

**Comment by mehmetg** [comment]
@jls I have assumed that there was a change when I added console outputs with the reporter function and observed that the callback was undefined rather than a function when reporter hook is called.  There was a runtime error about it that prompted me to look into it.
I am not sure if I have a good enough understanding of the flow, so I'll take a closer look and report back. Thank you for checking it out!

```javascript
module.exports = {
  reporter : function(results, done) {
    console.log(results);
    console.log(done);
    done();
  }
};
```

**Comment by jls** [comment]
I can't find any more info about it :(.  I'm going to close this out and if you run into the problem more or if they change the results then we can re-open or start a new one!
