### ISSUE TITLE
Show/Hide Successes link not functional

### ISSUE THREAD

**Issue by shanep2300** [jls/nightwatch-html-reporter#40]
Viewing on Chrome, nothing happens. 

Is this like an expand/collapse all function or will it keep the failures collapsed? If it's the latter, can you add an expand all function?

**Comment by jls** [comment]
It's supposed to be an expand collapse. I'll take a look and see why it's failing.  Are you using the default theme?

**Comment by shanep2300** [comment]
Using compact. I'll check with the default theme tomorrow. Might just use that theme anyways.

**Comment by jls** [comment]
Tested this on Chrome 57.0.2987.110 and the link seemed to be working for me.  But I think I misunderstood what you were asking originally.  The Show/Hide Successes should either remove all successful tests from the list or show successful tests in the list.  It doesn't affect whether any tests are collapsed or not.

**Comment by shanep2300** [comment]
Oh! So, since I only have one test, nothing is happening as then it will just show a blank page. Ok. I get it now. I thought it was to collapse/expand the test steps not the entire test. :)

**Comment by jls** [comment]
Ok awesome, have a great weekend!
