### ISSUE TITLE
[Suggestion] - local script & styles

### ISSUE THREAD

**Issue by tadessetdk** [jls/nightwatch-html-reporter#42]
Some of the themes refer to script or style files from the web, see below. Is it possible to add them as npm dependencies to the reporter, and themes will refer to local path in node_modules? Internet may not be available to all build environments.

https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js
https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css

Thanks

**Comment by jls** [comment]
Absolutely. I've been meaning to replace both of those with inline styles
and scripts.

What the themes use the styles and jQuery for is so minimal it doesn't make
sense to include the full libs.

Thanks for the case!

**Comment by tadessetdk** [comment]
Thanks.

Jenkins does not allow script and CSS file reference or inline to be used in the iframe by default. You have to enable them with Jenkins startup settings, which is not safe as it could expose other jobs.

Basically I ended up writing an HTML4 reporter with a bunch of nested <table/tr/td> with bgcolor, cellpadding, cellspacing, border attributes..., and <font> and <strong> tags for font color, size, weight... 

You inspired me, so thanks again.

**Comment by jls** [comment]
That's great!  I think the 'outlook' theme is kind of similar to what you are talking about although even it has inline styles and such.  Thanks for the issue and have a great weekend!
