### ISSUE TITLE
Using with another reporter

### ISSUE THREAD

**Issue by aamorozov** [jls/nightwatch-html-reporter#43]
@jls is there a way to use it with another reporter such as slack ?  Or it is a nightwatch limitation itself ?  For now, if I specify both in globals the second one is not getting called.

**Comment by jls** [comment]
I believe you would need to do something similar to [using the --reporter option](https://github.com/jls/nightwatch-html-reporter#using-nightwatch---reporter-option).  Basically just writing a function that would call both of the reporters.

```js
var HtmlReporter = require('nightwatch-html-reporter');
var htmlReporter = new HtmlReporter({
  openBrowser: true,
  reportsDirectory: __dirname + '/reports/'
});

/* The other reporter that you want to use */
var otherReporter = require('some-other-reporter');

module.exports = function(results, done) {
  htmlReporter.fn(results, function() {
    otherReporter(results, done);
  });
}
```

Then you can set that function as the reporter option in Nightwatch globals.

Hope that makes sense, good luck!
