### ISSUE TITLE
Failure not displayed

### ISSUE THREAD

**Issue by mattisback** [jls/nightwatch-html-reporter#48]
When I run some tests and they fail, nightwatch-html-reporter shows the assertions that passed but does not display the failed assertion.

Here's the output from nightwatch-html-reporter
![bad output html reporter](http://i67.tinypic.com/24zkd2v.png)

Here's the console output from nightwatch
![nightwatch console output](http://i67.tinypic.com/el604k.png)

**Comment by jls** [comment]
Sorry for the delay on this!  I've tried to reproduce this but I still see all of the errors using the cover theme.  Do you see any of the failures if you use the default theme?

**Comment by mattisback** [comment]
I get the same problem with the default theme.  Is there's something special I'm supposed to do to make errors show up?
Is `throw`ing an `Error` enough?

**Comment by mattisback** [comment]
It clearly knows that the test failed, just it's not showing the failure info.  I would have thought if there was an uncaught exception/error then the message from it would be displayed in the report?

For example:
```js
    if (! (userKey in users)) {
        console.log(chalk.red(' ✖ Could not login with user: key "' + userKey + '" does not exist in "users".'));
        throw new Error('Could not login with user: key "' + userKey + '" does not exist in "users".');
    }

    loginUser = users[userKey];
    console.log(chalk.cyan('Logging in with ' + loginUser.name + '...'));
```

**Comment by mattisback** [comment]
Also tried `return this.fail(false, true, ' ✖ Could not login with user: key "' + userKey + '" does not exist in "users".');` to no avail.

**Comment by jls** [comment]
When there is an error thrown it is marked as a failure but the assertion failure is blank.  Try using one of the asserts and see if you see the failure reason then.  Similar to:

```javascript
browser
    .url("http://www.google.com")
    .waitForElementVisible('body', 1000)
    .setValue('input[type=text]', 'nightwatch')
    .waitForElementVisible('button[name=btnG]', 1000)
    .click('button[name=btnG]')
    .pause(1000)
    .assert.containsText('#main', 'The Night Watch')
    .end();
```
