### ISSUE TITLE
error reading reports folder

### ISSUE THREAD

**Issue by axelbarfod1** [jls/nightwatch-html-reporter#49]
Hey guys, I followed the steps as described on the readme but im having the following error when trying to read the report folder here is an output of the error:

```
Reading reports directory...
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'name' of undefined

```
these are the libraries im using for nightwatch:

`"nightwatch": "0.9.14",
    "nightwatch-cucumber": "8.2.6",`

**Comment by jls** [comment]
Uh oh, this usually means Nightwatch changed the format of their XML files. I'll take a look as soon as I'm back in town. Thank you!

**Comment by axelbarfod1** [comment]
When you get some new about it let me know! Thanks on the reply!

**Comment by jls** [comment]
Hello @axelbarfod1, I'm not able to see the problem here.  Would you mind sending me one of your report XML files that I can use to try and reproduce?  You can email it to dev@jls.io if you'd rather not post it here.  Thanks!

**Comment by SammyGH** [comment]
Hi is there a away where can I see the total test failed/passed and total time of execution? (not the assertions) Thanks!

**Comment by jls** [comment]
Unfortunately I don't think we receive that info from Nightwatch.  Although it may be in one of the latest versions.  I can double check that.
