### ISSUE TITLE
Is there any option to see failure screenshots in the generated html report?

### ISSUE THREAD

**Issue by sushantwingified** [jls/nightwatch-html-reporter#50]
If yes, how. I am not able to see any option regarding it.

I am using cli to generate html report.

Directory structure
-reports
  -testname folder
     - screenshot saved
  - xml report file

**Comment by martineez** [comment]
Hi,
see how to enable screenshots in http://nightwatchjs.org/guide
nightwatch-html-reporter has just an option -r regarding absolute/relative path 
see also my[ multiple screenshots fix commit](https://github.com/jls/nightwatch-html-reporter/commit/aa813458be91a6bce9c32232efbc4f805e50285c)

**Comment by jls** [comment]
Let me know if @martineez suggestion didn't fix it for you and I can take a look!

**Comment by sushantwingified** [comment]
Hey, @jls  I figured that nightwatch does not attach screenshots in junit XML file for failures.
Refer this - https://github.com/nightwatchjs/nightwatch/issues/1463
Is there any workaround for this problem?

**Comment by jls** [comment]
Not that I know of :(  Looking at filename format and such I'm not sure how I could infer it even if we searched the screenshots directory.  Thanks for linking that issues to this one, that'll help keep track of it.
