### ISSUE TITLE
Assertions, visibility and other tests passed not displayed.

### ISSUE THREAD

**Issue by Visakeswaran** [jls/nightwatch-html-reporter#52]
I am using test functions [say login()], which has some assertions and wait functions, inside /pages/utils.js, and using these function inside various tests under the tests folder

'login' : function(Browser){
utils(browser).login();
}

While running the test the assertions are ran and the test is passed when i generate a report, it just shows 'login' passed, there is no info about the assertions passed.

**Comment by jls** [comment]
Are you generating a report from XML files or using the `reporter` option within nightwatch?  I'm not sure why you wouldn't see your assertions that have passed.  If you put the assertions directly in the 'login' function do you see them then?  I don't know why that would make a difference.

**Comment by jls** [comment]
Also are you using the built in nightwatch assertions, or an external assertion library like chai?  I seem to recall at one point nightwatch didn't count assertions from external libs so they were just showing pass/fail for those tests.

**Comment by Visakeswaran** [comment]
@jls is am using the built in assertion functions and generating a reports in JSON format using custom reporter package called 'Mocha-Awesome'.

**Comment by jls** [comment]
Hi @Visakeswaran!  Generating the reports in a JSON format may be part of the problem if you are using those reports to try and generate HTML reports.  This package depends on the XML files generated by nightwatch if you use it from the command line.

One way you might be able to get around that is by using the built in reporter option to pass the report data from nightwatch to both the Mocha-Awesome reporter and this reporter (https://github.com/jls/nightwatch-html-reporter#using-built-in-nightwatch-reporter).

Hope this helps!
