### ISSUE TITLE
can we configured this reporter with jest?

### ISSUE THREAD

**Issue by avne31** [jls/nightwatch-html-reporter#53]
hi,

I am looking for HTML reporter which can append test cases not to override the previous test cases.
presently I'm working on jest with Frisby's scripts and want HTML reporter of my scripts which can append all test result. So it is configurable with jest or not?

thanks

**Comment by jls** [comment]
At the moment the reporter only generates reports from either XML files or a reporter object from Nightwatch.js.  I'm not sure how to make that work with Jest, although I'm open to any pull requests that would if it ties in to Nightwatch.js!
