### ISSUE TITLE
Total testsuite run time

### ISSUE THREAD

**Issue by rourich** [jls/nightwatch-html-reporter#56]
I do not see an option to include the total test suite run time in the html reporter file. Will this feature be added? If not, are there any docs that I can refer to do create a new theme that will include this?

**Comment by jls** [comment]
That's a great suggestion!  As far as I know, we aren't given that information in either the XML files or the report data generated by Nightwatch (see [here for example of report data](https://github.com/jls/nightwatch-html-reporter/blob/master/test/mockdata/nightwatchReportObjects.js), and see [here for example xml file](https://github.com/jls/nightwatch-html-reporter/blob/master/test/mockdata/xmlreport.xml)).  

If you're able to find that info in a later version of Nightwatch then I'm completely open to a PR that adds it!

**Comment by rourich** [comment]
@jls 

cool! i think it would be super beneficial. actually! the xml file contains the total run time of a test suite!

check this out:

`  <testsuite name="test"
    errors="0" failures="1" hostname="" id="" package="test" skipped="0"
    tests="1" time="11.51" timestamp="Wed, 11 Jul 2018 20:09:10 GMT">`

The _time_ field indicates the total run time of all the test cases inside the specific test suite.

**Comment by Meghrikyan** [comment]
> @rourich awesome! Which version of Nightwatch are you using?

\- "nightwatch@0.9.21"

I tried to solve it locally by modification in /lib/themes/default/report.pug the following line:
h3.name= suite.name => **h3.name= suite.name + ' - (' + suite.time + 's)'**

But would be better to have total time at the end of the report as well.
