### ISSUE TITLE
Discerning between groups, files, and steps

### ISSUE THREAD

**Issue by tugend** [jls/nightwatch-html-reporter#6]
In the current themes, e.g. compact, it would be really nice overview to have a hiearachy of collapsable groups, files, steps, and assertions like follows.  

~~~
> navigation [success]
> filtering [failure]
>> filter.foo [success]
>> filter.bar [failure]
>> >> step.1 [sucess]
>> >> step.2 [sucess]
>> >> step.3 [failure]
>> >> >> assert 1 [success]
>> >> >> assert 2 [failure]
>> filter.bas [success]
>> testfile.4  [success]
>> testfile.5  [success]
> options [success]
> group.4 [success]
> group.5 [success]
~~~

What do you think? ^_^

**Comment by jls** [comment]
The current hierarchy starts at steps so this would be adding Groups/Files above the steps?

If so I think we could do that.  I think both the CLI and the reporter interface both get that information but I would have to double check.

**Comment by bbottema** [comment]
Currently I'm only concerned with grouping the steps by their parent test package. The default style indicates the package underneath each step, which should actually be the parent of those steps.

**Comment by jls** [comment]
I'm working on an update to all of the themes that will group results by the test package as well as clean up some of the styles. The only exception is the Cover theme which I wanted to keep in a flat list to quickly identify test failures without having to dig down into packages and suites. 

I should be able to get it tested and pushed in the next couple of days. Thank you both!

**Comment by jls** [comment]
Version 0.2.11 has the tests grouped by package.  Thanks again!

**Comment by tugend** [comment]
The new presentation structure looks fantastic and works as expected! =D

**Comment by bbottema** [comment]
Nice, works for us.
