### ISSUE TITLE
The reports don't work when hosted

### ISSUE THREAD

**Issue by bbottema** [jls/nightwatch-html-reporter#8]
I'm using this reporter in our continuous integration build server, but the report only works when opened from file system. So when the build server grabs the report to make it available after a build, the report is unable to load the script and css as they are referenced by file protocol instead of http. As it is, the reports are unusable for us.

**Comment by jls** [comment]
Hm I hadn't considered the case that the report would be opened on a different machine than it was generated on.  I'm working on an update right now that will inline the styles and javascript for all the themes.

**Comment by jls** [comment]
Version 0.2.10 addresses this by moving the styles and javascript inline so the report can be moved around.  Let me know if you have any problems, thank you!

**Comment by bbottema** [comment]
Verified, looks good!
