### ISSUE TITLE
[feature request] Groups

### ISSUE THREAD

**Issue by tugend** [jls/nightwatch-html-reporter#9]
I like to group my tests in groups and use the folder hiearachy to organize them.
This is supported by nighwatch through the --group flag which me to run one or 
specific test folder or group of tests. 

I imagine the benefit of this is a better understanding of what fails,
e.g. if the group network-connection-tests is the only group with failure
it would be easier to determine the problem.

It would be nice if this was included in one of the themes as an additional hiearachy.

**Comment by tugend** [comment]
The *.xml files only include package name - which seems to match the filename of the test file.
To include groups it would be neccessary to parse the paths of the xml files and group these.

**Comment by jls** [comment]
I could add an option to the CLI that supports groups.  Do you know if Nightwatch supports multiple levels of groups?  So if you had the folder structure MyGroup1 -> MySubGroup1 -> MySubGroup2 -> TextFile.xml could you run nightwatch --group MyGroup1/MySubGroup1? Or does it only support one level?  I'll look through their docs to see if they say.

**Comment by tugend** [comment]
Yup, your're quite right. =)
All tests in mytestdir/foo/bar/ can be targeted using 

~~~
nightwatch -g foo/bar
~~~

That is assuming that the .js test files are in the folder and not the output .xml files of course. o_O

**Comment by jls** [comment]
Ok awesome.  Yeah I meant TestFile.js not .xml, sorry about that.  It may be a while before I get to this but I'll look into it!

**Comment by jls** [comment]
I'm going to close this issue just because there haven't been other requests for nested groups and it looks like you've implemented a version that's working for you!

**Comment by tugend** [comment]
Cheerio. A-okay.
